### ISSUE TITLE
panic when marshal struct 

### ISSUE THREAD

**Issue by hsiven** [thrift-iterator/go#11]
The code below will panic:

```
package main

import (
	"fmt"

	"github.com/thrift-iterator/go"
)

type Foo struct {
	Sa string   `thrift:"Sa,1" json:"Sa"`
	Ib int32    `thrift:"Ib,2" json:"Ib"`
	Lc []string `thrift:"Lc,3" json:"Lc"`
}

type Example struct {
	Name string          `thrift:"Name,1" json:"Name"`
	Ia   int64           `thrift:"Ia,2" json:"Ia"`
	Lb   []string        `thrift:"Lb,3" json:"Lb"`
	Mc   map[string]*Foo `thrift:"Mc,4" json:"Mc"`
}

func main() {

	var example = Example{
		Name: "xxxxxxxxxxxxxxxx",
		Ia:   12345678,
		Lb:   []string{"a", "b", "c", "d", "1", "2", "3", "4", "5"},
		Mc: map[string]*Foo{
			"t1": &Foo{Sa: "sss", Ib: 987654321, Lc: []string{"1", "2", "3"}},
		},
	}

	fmt.Printf("example: %v\n", example)
	_, err := thrifter.Marshal(example)

	if err != nil {
		fmt.Printf("err: %v\n", err)
	}
}

```
the panic msg is below:

  

> example: {xxxxxxxxxxxxxxxx 12345678 [a b c d 1 2 3 4 5] map[t1:0xc000132450]}
panic: runtime error: growslice: cap out of range
goroutine 1 [running]:
github.com/thrift-iterator/go/protocol/binary.(*Stream).WriteString(0xc000148000, 0xbcce73b5c2737373, 0x203d2120bdbfef73)
	/data01/xuhuaye/go/src/github.com/thrift-iterator/go/protocol/binary/stream.go:164 +0x116
github.com/thrift-iterator/go/binding/reflection.(*stringEncoder).encode(0xa79998, 0x6cceed, 0x6ff940, 0xc000148000)
	/data01/xuhuaye/go/src/github.com/thrift-iterator/go/binding/reflection/encode_simple_value.go:24 +0x4a
github.com/thrift-iterator/go/binding/reflection.(*structEncoder).encode(0xc00000d180, 0x6cceed, 0x6ff940, 0xc000148000)
	/data01/xuhuaye/go/src/github.com/thrift-iterator/go/binding/reflection/encode_struct.go:35 +0x156
github.com/thrift-iterator/go/binding/reflection.(*pointerEncoder).encode(0xc00000d1a0, 0xc000132450, 0x6ff940, 0xc000148000)
	/data01/xuhuaye/go/src/github.com/thrift-iterator/go/binding/reflection/encode_pointer.go:20 +0x87
github.com/thrift-iterator/go/binding/reflection.(*mapEncoder).encode(0xc000132510, 0xc000132420, 0x6ff940, 0xc000148000)
	/data01/xuhuaye/go/src/github.com/thrift-iterator/go/binding/reflection/encode_map.go:30 +0x2da
github.com/thrift-iterator/go/binding/reflection.(*structEncoder).encode(0xc00000d1c0, 0xc0000bcc00, 0x6ff940, 0xc000148000)
	/data01/xuhuaye/go/src/github.com/thrift-iterator/go/binding/reflection/encode_struct.go:35 +0x156
github.com/thrift-iterator/go/binding/reflection.(*valEncoderAdapter).Encode(0xc0000107a0, 0x6aed20, 0xc0000bcc00, 0x6ff940, 0xc000148000)
	/data01/xuhuaye/go/src/github.com/thrift-iterator/go/binding/reflection/unsafe.go:45 +0x51
github.com/thrift-iterator/go.(*frozenConfig).Marshal(0xc000136000, 0x6aed20, 0xc0000bcc00, 0x6aed20, 0xc0000bcc00, 0xc0000a9f18, 0xc0000bcc00, 0xc0000bcc00)
	/data01/xuhuaye/go/src/github.com/thrift-iterator/go/config.go:251 +0x175
github.com/thrift-iterator/go.Marshal(0x6aed20, 0xc0000bcc00, 0x6aed20, 0xc0000bcc00, 0x1, 0x4e, 0x0)
	/data01/xuhuaye/go/src/github.com/thrift-iterator/go/api.go:72 +0x49
main.main()
	/data01/xuhuaye/go/src/iven_learn/test_thrifter/test.go:34 +0x317
exit status 2

**Comment by taowen** [comment]
This should fixed it https://github.com/thrift-iterator/go/commit/9b5a67519118594d9dea59cc6d75f5f64583bd3f

There might be more edge cases like this. The fundamental problem is how `interface{}` store the pointer. If the value itself is a pointer, it will not be stored as pointer to pointer, but embed directly into the `interface {}`. This is not a problem if using https://github.com/modern-go/reflect2 instead of reflect package which uses `interface {}`. But changing the reflection api of the package to match https://github.com/json-iterator/go is a much bigger project.
